CMD_RESET = 0xa1
CMD_GET_BATTERY = 0xb5
# CMD_GET_CHARGE = 0xb6 - unused
CMD_GET_SOFTWARE_VERSION = 0xb7
CMD_GET_UID = 0xba
CMD_RESET_WITH_COLOR = 0xa4
CMD_GET_ALL_STEP = 0xcc
CMD_GET_CLOCK = 0xc8
CMD_SET_CLOCK = 0xc9
CMD_START_COUNT = 0xca
CMD_GET_COUNT = 0xcb

CMDS = [ CMD_RESET, CMD_GET_BATTERY, CMD_GET_SOFTWARE_VERSION, CMD_GET_UID, CMD_RESET_WITH_COLOR, CMD_GET_ALL_STEP, CMD_GET_CLOCK, CMD_SET_CLOCK, CMD_START_COUNT, CMD_GET_COUNT ]